name: sqlitemodel
description: "SQLite model repository"
version: 1.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  sqflite_common_ffi: any
  sqlite3_flutter_libs: ^0.5.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:

